services:
  backend:
    build: .
    container_name: fractalis-backend 
    environment:
      PORT: ${PORT} 
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      NEO4J_HOST: fractalis-neo4j
      NEO4J_HTTP_PORT: 7474
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5002:${PORT}"
    volumes:
      - ./src:/app/src
    depends_on:
      fractalis-postgres:
        condition: service_healthy
      fractalis-neo4j:
        condition: service_healthy
    networks:
      - fractalis-network

  fractalis-postgres:
    image: postgres:16-alpine
    container_name: fractalis-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
    - fractalis-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fractalis-network

  fractalis-neo4j:
    image: neo4j:5
    container_name: fractalis-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - fractalis-neo4j-data:/data
      - ./database/neo4j:/var/lib/neo4j/import
    healthcheck:
      # Usamos wget para ver si el puerto 7474 responde, es más ligero que cypher-shell
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 15s      # Más tiempo entre pruebas
      timeout: 10s
      retries: 10        # Más intentos para dar tiempo a los plugins
      start_period: 30s
    entrypoint: >
      /bin/bash -c "
      (sleep 20 && cypher-shell -u ${NEO4J_USER} -p ${NEO4J_PASSWORD} -f /var/lib/neo4j/import/init.cypher && echo '✅ Neo4j inicializado') &
      /startup/docker-entrypoint.sh neo4j"
    networks:
      - fractalis-network

  flyway:
    image: flyway/flyway
    container_name: fractalis-flyway
    command: -connectRetries=60 migrate
    volumes:
      - ./database/migrations:/flyway/sql
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
    depends_on:
      fractalis-postgres:
        condition: service_healthy
    networks:
      - fractalis-network

networks:
  fractalis-network:
    name: fractalis-network
    driver: bridge

volumes:
  fractalis-postgres-data:
  fractalis-neo4j-data: